[package]
name = "file-explorer"
version = "0.1.0"
edition = "2021"
license = "MIT"
authors = ["asd759"]

[dependencies]
iced = "0.13.0"
sysinfo = "0.33.0"
walkdir = "2.5.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"